######################################################################
# Automatically generated by qmake (3.0) Tue Mar 24 11:38:39 2020
######################################################################

TEMPLATE = app
TARGET = szopinski-egui
INCLUDEPATH += .
DESTDIR = bin
OBJECTS_DIR=obj

# Input
SOURCES += main.cpp calendar.cpp eventcalendar.cpp eventeditor.cpp entryeditor.cpp
HEADERS += calendar.h eventcalendar.h
FORMS += entryeditor.ui
QT += widgets
